#!/bin/bash

python semantic.py --batch_mode ../test_fixtures/test/speech --validate_output ../test_fixtures/sol/speech
python semantic.py --batch_mode ../test_fixtures/test/complex_speech --validate_output ../test_fixtures/sol/complex_speech
python semantic.py --batch_mode ../test_fixtures/test/log --validate_output ../test_fixtures/sol/log
python semantic.py --batch_mode ../test_fixtures/test/multiword --validate_output ../test_fixtures/sol/multiword
